### ISSUE TITLE
why are the item icons sell by the same player the same?

### ISSUE THREAD

**Issue by ProjectSky** [xKaYoz/AkarianAuctionHouse#7] opened 2023-01-25 05:15 UTC
icon changes when trying to remove, server console doesn't report any errors
![UI2](https://user-images.githubusercontent.com/16351827/214485425-653ea03d-b98a-4c22-82f6-5f7efce70c50.gif)

**Comment by xKaYoz** [comment] 2023-01-26 16:37
Hey there @ProjectSky!

I apologize about this bug, This was a stupid mistake on my part failing to increment. I will have this fixed in the update coming out later today.

Thank you very much!

**Comment by ProjectSky** [comment] 2023-01-27 00:50
> Hey there @ProjectSky!
> Thank you very much!

no thanks, I love this plugin

* another bug:
If the player gets any items after opening the auction house inventory, the items will disappear after closing the menu

**Comment by xKaYoz** [comment] 2023-01-27 15:24
Hey there @ProjectSky!

I've been trying to recreate this bug but I am having no luck. Would you please walk me through how you ran into this bug?

Thanks!

**Comment by ProjectSky** [comment] 2023-01-27 16:39
> Hey there @ProjectSky!
> 
> I've been trying to recreate this bug but I am having no luck. Would you please walk me through how you ran into this bug?
> 
> Thanks!

weird, I can't recreate it
maybe it only triggers special conditions, if I find a way to recreate this bug, I'll let you know

**Comment by ProjectSky** [comment] 2023-01-28 12:31
> Hey there @ProjectSky!
> 
> I've been trying to recreate this bug but I am having no luck. Would you please walk me through how you ran into this bug?
> 
> Thanks!

in layout editing mode, any new items will be lost after closing editing

![UI2](https://user-images.githubusercontent.com/16351827/215266422-756273f7-c66f-4847-bcef-4bf8b47ff2ff.gif)

**Comment by xKaYoz** [comment] 2023-01-28 19:36
Hey there @ProjectSky!

What actions did you take before you closed the menu? It looks like something triggered it to give you your inventory with the editor opened.

Thanks!

**Comment by xKaYoz** [comment] 2023-01-28 20:09
Hey there @ProjectSky!

I was able to root out the cause to me giving the player their inventory when clicking the close button and clearing the data. I have a check to give the player their inventory when the layout editor is closed incase something were to happen and it would then give you the cleared data for your inventory. I will have the new update posted shortly!

Thanks for the continued reports!

**Closed as completed by xKaYoz** 2023-01-28 20:09 UTC
Labels: bug
